
[terminal.shell]
program = "/usr/bin/zsh"

[window]
dynamic_title = true
opacity = 0.9

[keyboard]
bindings = [
    {key = "ArrowUp", mods = "Shift", action = "ScrollLineUp" },
    {key = "ArrowDown", mods = "Shift", action = "ScrollLineDown" }
]
